### ISSUE TITLE
Migration to Gymnasium 

### ISSUE THREAD

**Issue by Dhanushvarma** [corl-team/CORL#14]
How exactly do I do roll outs with the trained policy with rendering? Is that naively easy to do, or requires work?

**Comment by DT6A** [comment]
@Dhanushvarma I think it's easy and  you just need to find out how the rendering is done for the particular environment. It shouldn't depend on the policy you use. Try to check this out: https://gymnasium.farama.org/api/env/#gymnasium.Env.render
