### ISSUE TITLE
CQL Hopper normalizing reward

### ISSUE THREAD

**Issue by modanesh** [corl-team/CORL#17]
In the config files for CQL and Hopper, for every dataset, the `normalize_reward` is set to `false`, while only in `medium_v2.yaml` it is set to `true` [(medium_v2.yaml)](https://github.com/corl-team/CORL/blob/main/configs/offline/cql/hopper/medium_v2.yaml). I'm wondering if it's set to true by mistake or it's intentional. If it's intentional, why it's only normalizing rewards for medium_v2 and not other datasets?

Thanks.

**Comment by DT6A** [comment]
@modanesh thanks for noticing it! I think it just a random mistake. When `normalize_reward` is `true` it transforms reward with `reward_scale` and `reward_bias` which are set to 1 and 0 for hopper. So it doesn't have any effect on the reward.

**Comment by modanesh** [comment]
Thanks for the explanation! That makes sense, that's why I created the issue in the beginning.
